package common;

public enum CommandIDs {
    REQUEST_AUTHDATA,
    REQUEST_FILELIST,
    REQUEST_MKDIR,
    REQUEST_UPTODIR,
    REQUEST_CHANGEDIR,
    REQUEST_FILEDATA,
    RESPONCE_FILELIST,
    RESPONCE_FILEDATA,
    RESPONCE_AUTHOK,
    RESPONCE_AUTHERROR,
    RESPONCE_CONNECTIONERROR,
    RESPONCE_FILERECIEVED
}
