package common;

public enum CommandIDs {
    REQUEST_AUTHDATA,
    REQUEST_FILELIST,
    REQUEST_CURRENTFOLDER,
    REQUEST_MKDIR,
    REQUEST_UPTODIR,
    REQUEST_CHANGEDIR,
    REQUEST_SENDFILE,
    REQUEST_FILERECIEVED,
    RESPONCE_FILELIST,
    RESPONCE_CURRENTFOLDER,
    RESPONCE_AUTHOK,
    RESPONCE_AUTHERROR,
    RESPONCE_ACCESSDENIED,
    RESPONCE_CONNECTIONERROR,
    RESPONCE_UNEXPECTEDCOMMAND,
    RESPONCE_SERVERERROR,
    RESPONCE_FILERECIEVED
}
